feat(cardeditor): initial drop of experimental component
carbon-design-system/carbon-addons-iot-react pull request #1596
Opened 2020-09-12 19:57 UTC by bryancboyd

**Summary**

This PR provides an initial implementation that covers work for the following issues:

#1560 
#1561 
#1562 
#1563 

We'll provide further improvements and additions to this component over the next 2 weeks, but the component delivered in this PR is functional enough to start being imported and used by applications

**Change List (commits, features, bugs, etc)**

- Added new Experimental component `<CardEditor>`

**Acceptance Test (how to verify the PR)**

- Jest tests pass
- Click around the storybook `<CardEditor>`interactive story.  The JSON editor allows you to fully modify the JSON definition of the card, and the card edit form will provide inputs to modify card size and title.  If no card definition is passed to CardEditor, the component opens in "gallery mode" where the user can select a card type from a list.

The interactive story also renders the card definition JSON on the left side of the screen, updated in response to the `onChange` event defined on CardEditor.

![image](https://user-images.githubusercontent.com/2175647/93003912-2951ed80-f508-11ea-9b85-e741f619c07e.png)

2020-09-13 15:26 UTC, sstone2423 requested changes
Looks good, but is there any kind of state to go back to the existing card that is being editted? If you start in the default story, then click `view gallery`, theres no way of going back to the existing card that is being editted

2020-09-13 15:26 UTC, sstone2423 commented on src/components/CardEditor/CardEditForm/_card-edit-form.scss
> +      height: 30rem;
This can be added to the actual TextArea component with the `columns` prop

2020-09-13 21:26 UTC, bryancboyd commented
Yeah, in fact I was thinking about removing the showGallery state from the component completely and replacing with a callback (onShowGallery) so that the implementer can manage the "mode" of the editor component (add (gallery) or edit (form)). I'll do that for now.

In proposed "Dashboard Editor" patterns I've seen, the Card Editor would default to the "gallery" state when no cards are selected on the preview dashboard. Then, when either A) a user selects an existing card, or B) a user selects a card type from the gallery, the editor would switch over to the "form" state. With this behavior, selecting "View gallery" would essentially deselect the currently-editing card.

(I wouldn't be surprised if the "view gallery" button gets removed by the time we are finished)

2020-09-14 14:57 UTC, sstone2423 approved these changes

2020-09-16 18:34 UTC, filipecorrea submitted a review, later dismissed
`Table` and `TableViewDropdown` snapshots needs to be updated.

2020-09-17 20:52 UTC, tay1orjones approved these changes
looks great!

2020-09-17 20:52 UTC, tay1orjones commented on src/components/CardEditor/CardEditor.test.jsx
> +        name: CardEditor.defaultProps.i18n.openGalleryButton,
love this, great idea to use the default props

2020-09-17 23:28 UTC, merged

2020-09-17 23:47 UTC, tay1orjones commented
:tada: This PR is included in version 2.120.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.120.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: