feat(table): added option alwaysTruncate (no refactor)
carbon-design-system/carbon-addons-iot-react pull request #1651
Opened 2020-10-05 14:16 UTC by bjornalm

Closes #1196

**Summary**
The wrapCellText prop could have the values:
• ‘auto’ we apply wrapping only for tables with normal columns. For tables with fixed or resizable columns we use truncation.
• ‘always’ we wrap in all scenarios including tables with fixed or resizable columns (i.e. current situation).
• ‘never’ we never wrap and as a consequence the tables with normal columns* get wide cells and more often horizontal scrolling. For tables with fixed or resizable columns we use truncation.

Feedback and questions shows to some confusion where app developers want to force text truncation for non resizable/fixed width tables. So we added the option `alwaysTruncate` to support this.

See #1196 for more context

**Change List (commits, features, bugs, etc)**
- Added option alwaysTruncate
- Added more unit tests

**Acceptance Test (how to verify the PR)**
Nota bene! You might have to decrease the width of your browser window in order to trigger truncation of the table cell texts.

1. In general, verify that the table stories that have a wrapCellText knob will use truncation if the new 'alwaysTruncate' option us selected.

2. Especially, verify that stories that don't use hasResize and don't have fixed column widths still will truncate when the new 'alwaysTruncate' option us selected.
E.g. /story/watson-iot-table--stateful-example-with-multiselect-filtering

2020-10-05 14:59 UTC, stuckless approved these changes

2020-10-07 20:05 UTC, tay1orjones requested changes
One minor spelling correction 😄

2020-10-07 20:05 UTC, tay1orjones commented on src/components/Table/Table.jsx
> +     * alwaysTruncate - Alwyas truncate if needed for all table column configurations
```suggestion
     * alwaysTruncate - Always truncate if needed for all table column configurations
```

2020-10-07 20:05 UTC, tay1orjones approved these changes

2020-10-07 20:26 UTC, merged

2020-10-07 20:43 UTC, tay1orjones commented
:tada: This PR is included in version 2.130.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.130.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: