feat(list): add emptyState
carbon-design-system/carbon-addons-iot-react pull request #1654
Opened 2020-10-05 16:13 UTC by jonguenther

Closes #1653 

**Summary**

- Add `emptyState` to be shown if `items` are empty and `hasEmptyState` is enabled
- `emptyState` can be either text or a component
- Add default `emptyState` style (see screenshot). If only text is provided, the text in the screenshot will be overwritten by it.

**Change List (commits, features, bugs, etc)**

- Add `emptyState` prop which will be shown if `List` is empty. Can be either text or component
- Add `hasEmptyState` prop which determines whether `emptyState` should be displayed if `items` is empty. `false` by default
- Add CSS for `emptyState` text styling
- Set defaultProp for `items` to `[]`

**Acceptance Test (how to verify the PR)**

- List shows no empty text if not set
- List shows empty text if desired
- Renders custom component for empty state

**Screenshot**
![image](https://user-images.githubusercontent.com/23116024/95104276-ec0f0300-0735-11eb-81e6-486fe706c69e.png)

2020-10-05 16:15 UTC, jonguenther commented
On a related note: Would it make sense to create a (internal) component for empty states? That way we would have a consistent look for it (or does such a component already exist?)

2020-10-06 21:49 UTC, tay1orjones commented
@jonguenther good question - @dianatran18 have we thought about standardizing these empty states across the various components that use them?

2020-10-06 21:54 UTC, dianatran18 commented
Glad you asked @tay1orjones ! We actually just came out with some [empty state design guidance](https://pages.github.ibm.com/ai-applications/design/components/empty-states/usage/) to follow Carbon's standard more. 

Something I'd love to update in the PAL, and understand where these empty states are currently being used

2020-10-07 19:59 UTC, tay1orjones requested changes
Knowing that we'll be looking to configure the new Empty state guidance Diana mentioned above, I think we can keep the API a bit simpler by having just one prop.

2020-10-07 19:59 UTC, tay1orjones commented on src/components/List/List.jsx
> +  emptyState: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
`hasEmptyState` seems redundant here. If `hasEmptyState` is removed,`emptyState` can be unconditionally rendered when there are no items.

If someone desires for the empty state to be totally blank, they can configure `emptyState` to be an empty string.

```suggestion
  /** content shown if list is empty */
  emptyState: PropTypes.oneOfType([PropTypes.node, PropTypes.string]),
```

2020-10-07 19:59 UTC, tay1orjones commented on src/components/List/List.jsx
> +  emptyState: 'Empty list',
```suggestion
  emptyState: 'No list items to show',
```

Loosely based on [the guidance from the site](https://pages.github.ibm.com/ai-applications/design/components/empty-states/usage#data-missing)

2020-10-07 19:59 UTC, tay1orjones commented on src/components/List/List.jsx
> +          <>{listItems.length ? listItems : hasEmptyState && emptyContent}</>
```suggestion
          <>{listItems.length ? listItems : emptyContent}</>
```

2020-10-07 19:59 UTC, tay1orjones commented on src/components/List/List.story.jsx
> +        hasEmptyState={boolean('hasEmptyState', true)}
```suggestion
        emptyState={text('hasEmptyState', 'No list items to show')}
```

2020-10-12 11:02 UTC, tay1orjones approved these changes

2020-10-14 13:50 UTC, davidicus approved these changes
Good to go once CI checks have passed

2020-10-14 13:53 UTC, davidicus commented
Looks like we just need to run yarn install for  prettier to pass the travis check

2020-10-14 16:00 UTC, merged