[ListCard / SimpleList] bug fixes
carbon-design-system/carbon-addons-iot-react pull request #1692
Opened 2020-10-15 16:22 UTC by sstone2423

Closes #1689 #1690 #1691 

**Summary**

- Adds empty state for ListCard if there is no data
- Merges `i18n` prop with defaultProps `i18n`
- Adds ability to hide the pagination in SimpleList

**Change List (commits, features, bugs, etc)**

- Added story for empty state ListCard
- Added story for hidden pagination in SimpleList

**Acceptance Test (how to verify the PR)**

- Go to ListCard - empty story to see empty state
- Go to SimpleList - hidden pagination story to see hidden pagination
- Go to any SimpleList story and only provide 1 `i18n` prop and the list should still render correctly

2020-10-15 17:12 UTC, JoelArmendariz commented
Looks like the empty state `ListCard` is ignoring width/card-size and is stretching across the container when empty.

![Screen Shot 2020-10-15 at 12 10 53 PM](https://user-images.githubusercontent.com/53092833/96163508-98dc4380-0edf-11eb-874a-1aa854f78511.png)

2020-10-15 18:14 UTC, sstone2423 commented
> Looks like the empty state `ListCard` is ignoring width/card-size and is stretching across the container when empty.
> 
> ![Screen Shot 2020-10-15 at 12 10 53 PM](https://user-images.githubusercontent.com/53092833/96163508-98dc4380-0edf-11eb-874a-1aa854f78511.png)

Fixed by add a width wrapper around the ListCard as we do in other Card stories

2020-10-15 18:31 UTC, JoelArmendariz approved these changes
LGTM

2020-10-15 19:06 UTC, scottdickerson approved these changes
LGTM

2020-10-16 11:07 UTC, tay1orjones requested changes
Just one small change for the sake of consistency. Thanks for removing all those empty `info` blocks!

2020-10-16 11:07 UTC, tay1orjones commented on src/components/List/SimpleList/SimpleList.jsx
> +  showPagination: PropTypes.bool,
In HierarchyList, Table, and a few other components this is typically named `hasPagination`. 
```suggestion
  hasPagination: PropTypes.bool,
```

2020-10-16 11:18 UTC, tay1orjones approved these changes
I went ahead and pushed an update to your branch to rename the prop 👍

2020-10-16 11:42 UTC, merged

2020-10-16 11:59 UTC, tay1orjones commented
:tada: This PR is included in version 2.134.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.134.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: