chore(charts): upgrade carbon charts to latest version and needs new color options
carbon-design-system/carbon-addons-iot-react pull request #1748
Opened 2020-11-02 22:53 UTC by scottdickerson

Closes #

**Summary**

- I updated @carbon/charts to the latest version and found that I now need to pass the carbon colors in the scale myself if they're not set by the user

**Change List (commits, features, bugs, etc)**

- fix(barChartUtils, TimeSeriesCard): update the formatColors payload to pass explicit colors in the scale options

**Acceptance Test (how to verify the PR)**

- Small regression test of the BarChartCard and TimeSeriesCard stories

2020-11-04 16:31 UTC, marcJV requested changes

2020-11-04 16:31 UTC, marcJV commented on src/constants/CardPropTypes.js
> +  // yellow50,
we should remove the commented colors, or uncomment them

2020-11-05 20:06 UTC, tay1orjones requested changes

2020-11-05 20:06 UTC, tay1orjones commented on package.json
> +    "@carbon/colors": "^10.15.0",
This should be pinned, not caret range.
```suggestion
    "@carbon/colors": "10.15.0",
```

2020-11-05 20:06 UTC, tay1orjones commented on src/constants/CardPropTypes.js
> +  // yellow50,
```suggestion
```

2020-11-05 20:06 UTC, tay1orjones commented on src/constants/CardPropTypes.js
> +  // yellow50,
```suggestion
```

2020-11-05 20:06 UTC, tay1orjones commented on src/constants/CardPropTypes.js
> +  // orange70,
```suggestion
```

2020-11-09 19:58 UTC, scottdickerson commented
@tay1orjones @marcJV I fixed the issues and the testcases, can you please take another look?

2020-11-10 12:28 UTC, tay1orjones approved these changes

2020-11-10 14:12 UTC, JoelArmendariz approved these changes
LGTM

2020-11-10 23:06 UTC, merged

2020-11-11 00:30 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0-next.9 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0-next.9)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0-next.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-12-15 18:46 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: