1695 add empty state component
carbon-design-system/carbon-addons-iot-react pull request #1793
Opened 2020-11-12 14:04 UTC by jonguenther

Closes #1695 

**Summary**

- Adds `EmptyState` component according to the carbon / AI-PAL guidelines

**Change List (commits, features, bugs, etc)**

- Add `EmpyState` component
- Add `EmptyState` icons for the different types of empty states
- Add story for component
- Add tests for component

**Acceptance Test (how to verify the PR)**

- run EmptyState.test.jsx

2020-11-12 19:15 UTC, tay1orjones requested changes
Overall looks good! A few comments below on the code. I'm going to push a couple small changes to your stories if that's alright with you.

2020-11-12 20:03 UTC, tay1orjones commented
In addition, based on guidance from @dianatran18, the actions shouldn't be fully customizable. We should only allow the buttons, not an open ended node/element.

2020-12-03 21:47 UTC, tay1orjones reviewed
Some comments to remove, but otherwise looks great - thanks!

2020-12-03 21:47 UTC, tay1orjones commented on src/components/EmptyState/EmptyState.test.jsx
> +  // });
```suggestion
```

2020-12-03 21:47 UTC, tay1orjones commented on src/components/EmptyState/EmptyState.jsx
> +          )} */}
```suggestion
```

2020-12-03 21:47 UTC, tay1orjones commented on src/components/EmptyState/EmptyState.jsx
> +          )} */}
```suggestion
```

2020-12-03 21:47 UTC, tay1orjones commented on src/components/EmptyState/EmptyState.jsx
> +  // ]),
```suggestion
```

2020-12-03 21:47 UTC, tay1orjones commented on src/components/EmptyState/EmptyState.jsx
> +  // ]),
```suggestion
```

2020-12-03 21:47 UTC, tay1orjones commented on src/components/EmptyState/EmptyState.jsx
> +// TODO: Discuss whether actions can be custom components, e.g. for showing details in error messages.
```suggestion
```

2020-12-03 21:52 UTC, tay1orjones approved these changes
Thanks again for this contribution! 🎉

2020-12-04 10:15 UTC, bjornalm approved these changes
Nice work, just a couple of comments.

2020-12-04 10:15 UTC, bjornalm commented on src/components/EmptyState/EmptyState.jsx
> +          <Button onClick={action.onClick && action.onClick}>
Why `action.onClick && action.onClick`? 
(We know there is an action and if there is an action then the `onClick` prop is required)

2020-12-04 10:15 UTC, bjornalm commented on src/components/EmptyState/EmptyState.jsx
> +            <Link onClick={secondaryAction.onClick && secondaryAction.onClick}>
See action.onClick comment

2020-12-07 19:40 UTC, merged

2020-12-07 19:53 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0-next.46 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0-next.46)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0-next.46)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-12-15 18:44 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: