feat(hotspot-text-style-tab): added text style tab
carbon-design-system/carbon-addons-iot-react pull request #1815
Opened 2020-11-18 00:15 UTC by marcJV

Closes #1768

**Summary**

- Added Hotspot Text Style Tab

**Acceptance Test (how to verify the PR)**

- Go to `?path=/story/watson-iot-experimental-hotspoteditormodal-hotspottextstyletab--default`
Verify design.
Verify updates update in the actions tab.

2020-11-18 09:40 UTC, bjornalm requested changes
Nice work! I have some suggestions though

2020-11-18 09:40 UTC, bjornalm commented on src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
> +          selectedColor={background.color ?? backgroundColors?.[0]}
Suggestion, skip the fallback `backgroundColors?.[0]` and just use `backgroundColor` which might be undefined which is okay.

2020-11-18 09:40 UTC, bjornalm commented on src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
> +              background: { opacity: fillOpacityRef.current.value },
It seemed weird that we would have to use a ref to obtain the value, so I looked at the emitted event and it appears that carbon has added an `imaginaryTarget` element prop that contains the value. So you could do something like

```
onChange={(event) => {
  onChange({ background: event.imaginaryTarget.value})
}}
```

2020-11-18 09:40 UTC, bjornalm commented on src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
> +  const fontSizeRef = useRef(null);
We can probably remove these refs, se comment below.

2020-11-23 14:11 UTC, bjornalm requested changes
It looks like several of the previous issues were marked as resolved without being fixed or commented on.

2020-11-23 14:11 UTC, bjornalm commented on src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
> +  /** The state values of the controlled form elements e.g. { title: 'My hotspot 1', description: 'Lorem ipsum' } */
There is no 'title' prop for the "formValues" object of this component...

2020-11-30 20:40 UTC, bjornalm commented
Look good. Just one thing I noticed the there are two RTL issues with the content switcher.


![image](https://user-images.githubusercontent.com/5167091/100662006-9da46c00-3354-11eb-9c89-2bb28b2bc253.png)


I've solved the text padding issue in this [pr](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1836) which also contained a mixin for the border radius. Perhaps we should move that mixin out so that it can be reused between components. Have a look here https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/src/components/ImageGalleryModal/_image-gallery-modal.scss#L3-L21

2020-11-30 22:53 UTC, tay1orjones approved these changes
Looks good once @bjornalm's feedback is addressed

2020-12-01 19:34 UTC, davidicus commented
@marcJV can we resolve these conflicts so this can be merged when @bjornalm reviews?

2020-12-01 21:37 UTC, bjornalm approved these changes

2020-12-01 22:00 UTC, merged

2020-12-01 22:12 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0-next.35 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0-next.35)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0-next.35)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-12-15 18:45 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: