feat(suiteheader): mroio and apm data
carbon-design-system/carbon-addons-iot-react pull request #1873
Opened 2020-12-10 13:28 UTC by hectordavis

**Summary**

- Adding **MRO Inventory Optimization** and **Asset Performance Management for Energy and Utilities** to `SuiteHeader` data

2020-12-10 13:30 UTC, cgirani approved these changes

2020-12-10 13:37 UTC, blechner requested changes
Please include mrio and apm mock apis in the fixtures file.

2020-12-10 19:23 UTC, blechner approved these changes

2020-12-11 16:05 UTC, merged

2020-12-11 16:19 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0-next.53 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0-next.53)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0-next.53)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-12-15 18:44 UTC, tay1orjones commented
:tada: This PR is included in version 2.141.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/carbon-addons-iot-react/v/2.141.0)
- [GitHub release](https://github.com/carbon-design-system/carbon-addons-iot-react/releases/tag/v2.141.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: