feat(combo-card): added combochart card
carbon-design-system/carbon-addons-iot-react pull request #1939
Opened 2021-01-14 14:58 UTC by marcJV

Closes #1483

**Summary**

- Adds a card wrapper for the Combo Chart

**Change List (commits, features, bugs, etc)**

- Added ComboCardChart component, stories, and tests

**Acceptance Test (how to verify the PR)**

Verify that the chart is rendered correctly at:
?path=/story/watson-iot-combochartcard--combo-chart-card-area
- Loading state is rendered correctly at:
?path=/story/watson-iot-combochartcard--combo-chart-card-loading
- Empty state is rendered correctly at:
?path=/story/watson-iot-combochartcard--combo-chart-card-empty

2021-01-22 15:01 UTC, sstone2423 requested changes

2021-01-22 15:01 UTC, sstone2423 commented on src/components/ComboChartCard/ComboChartCard.jsx
> +          data={values}
We do a lot of data formatting in BarChartCard and TimeSeriesCard as well as formatting the tooltip to fit our needs. I think this component will need the same util logic

2021-01-22 15:01 UTC, sstone2423 requested changes

2021-01-22 15:01 UTC, sstone2423 commented on src/components/ComboChartCard/ComboChartCard.jsx
> +  i18n: PropTypes.shape({
We'll need the same i18n as TimeSeriesCard and BarChartCard I think as we translate as many things as possible

2021-01-22 15:28 UTC, sstone2423 requested changes
There should also be an expand option that renders a table with all of the data being rendered. See the other chart cards for a reference

2021-01-27 15:52 UTC, davidicus commented
Opened #1976 to track bug with storyshot imports

2021-03-08 18:54 UTC, davidicus commented
closing. Dev will reopen in another PR since substantial changes have been made since first reviewed.

2021-03-08 18:54 UTC, closed without merging