fix(pagetitlebar): fix some alignment/spacing issues
carbon-design-system/carbon-addons-iot-react pull request #2208
Opened 2021-04-12 13:11 UTC by jkeen

Closes #2144 

**Summary**

- Verified colors and spacing in design doc and corrected irregularities according to [the spec sheet](https://github.com/carbon-design-system/carbon-addons-iot-react/files/6227340/Page.header.-.spec.sheet.pdf)

**Change List (commits, features, bugs, etc)**

- added new stories illustrating some of the scenarios
- Adjusted alignment of tabs in relation to title
- made accommodation for when `<InlineLoading>` is used as description
- Made sure spacing between buttons and search, selects, or other non-button objects in the toolbar have 16px margin.
- Single primary buttons should have a left margin, but primary + secondary next to each other should not have space between them

**Acceptance Test (how to verify the PR)**

- Compare relevant sections of the spec sheet with the output described above

2021-04-12 15:03 UTC, JoelArmendariz submitted a review, later dismissed
LGTM

2021-04-12 17:38 UTC, davidicus commented
Can we adjust the delay on the background color opacity? It takes too long and you can see the overlay before the background fills in.
https://user-images.githubusercontent.com/1590966/114428877-bd616180-9b8a-11eb-9dc5-c4fb2a0024f4.mov

2021-04-12 17:39 UTC, davidicus commented
In the issue for this PR the designer state the tabs should have the sticky effect instead of the header. It looks like it is always the header even with Tabs present.

2021-04-12 17:40 UTC, davidicus commented
The padding on top of breadcrumbs seems larger than the 12px of padding called for in the spec.

2021-04-12 23:21 UTC, davidicus commented
There seems to be several places where the spec is not being respected in this story [here](https://deploy-preview-2208--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-pagetitlebar--with-dynamic-scrolling). Tooltip icon does not have the proper size and there is some spacing issues.

2021-04-12 23:21 UTC, davidicus requested changes
There are a few items that still need to be addressed.

2021-04-14 15:15 UTC, davidicus commented
@Najil-K @dianatran18 Please review the PR for alignment.

2021-04-14 15:38 UTC, dianatran18 commented
Hey @davidicus should which one should we be reviewing specifically?

2021-04-14 16:03 UTC, davidicus commented
@dianatran18 [This](https://deploy-preview-2208--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-pagetitlebar--with-everything) story and [this](https://deploy-preview-2208--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-pagetitlebar--with-dynamic-scrolling) story would be good to check. The second one you have to adjust the knobs for the different forms of sticky header.

2021-04-15 08:54 UTC, Najil-K commented
**UI audit sheet:**

[UI audit - Page header.pdf](https://github.com/carbon-design-system/carbon-addons-iot-react/files/6316533/UI.audit.-.Page.header.pdf)

![UI audit - Page Title (v2)@2x](https://user-images.githubusercontent.com/81316430/114839281-395de280-9df3-11eb-8eec-dfd9b46fd3fd.jpg)



@davidicus @dianatran18

2021-04-21 14:33 UTC, davidicus requested changes
This looks good but we still need to fix the tooltip icon outlined in issue 5 outlined by @Najil-K.  FYI @Najil-K issue 4 is showing the focus blue ring which Carbon actually has in their storybook as well.

2021-04-28 13:13 UTC, davidicus commented on packages/react/src/components/PageTitleBar/PageTitleBar.jsx
> +  stickyHeaderOffset: 0, // default to 3rem to stick to the bottom of the suite header
Does this comment still apply here?

2021-04-29 13:34 UTC, davidicus approved these changes

2021-04-29 13:51 UTC, merged