feat(1821): new MenuButton component
carbon-design-system/carbon-addons-iot-react pull request #2217
Opened 2021-04-14 16:52 UTC by kevinsperrine

Closes #1821, #1443 

**Summary**

- integrates the ContextMenu from Carbon into a new MenuButton component that has groups, submenus, dividers, etc, etc.

**Acceptance Test (how to verify the PR)**

- https://deploy-preview-XXX--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-☢%EF%B8%8F-menubutton--single-menu-button
- https://deploy-preview-XXX--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-☢%EF%B8%8F-menubutton--split-menu-button
- https://deploy-preview-XXX--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-☢%EF%B8%8F-menubutton--icon-only-menu-button

2021-04-15 13:51 UTC, sstone2423 approved these changes
Looks great. Just the one question

2021-04-15 13:51 UTC, sstone2423 commented on packages/react/src/components/MenuButton/MenuButton.jsx
> +import { unstable_ContextMenu as ContextMenu } from 'carbon-components-react';
Is this due to it being deprecated or experimental?

2021-04-19 14:13 UTC, davidicus commented
We will want to make sure the icon only version follows the same visual treatment that the overflow menu does. So when open the icon should have same color background as dropdown.

2021-04-19 14:28 UTC, davidicus requested changes
This looks great!. We will probably want the drop down to be aware of its placement via the usePopupPosition hook. There are also a few RTL issues that need to be addressed.

2021-04-19 20:13 UTC, kevinsperrine commented
This is failing b/c of something on the angular side. 

```
@ai-apps/angular: Killed
@ai-apps/angular: error Command failed with exit code 137.
@ai-apps/angular: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ai-apps/angular: error Command failed with exit code 137.
@ai-apps/angular: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test:ci exited 137 in '@ai-apps/angular'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 137.
```

2021-04-21 14:41 UTC, davidicus commented
@kevinsperrine I am still seeing this RTL issue
![image](https://user-images.githubusercontent.com/1590966/115572664-1a959b00-a28e-11eb-9876-803654ad8ea6.png)

2021-04-21 14:46 UTC, kevinsperrine commented
> @kevinsperrine I am still seeing this RTL issue
> ![image](https://user-images.githubusercontent.com/1590966/115572664-1a959b00-a28e-11eb-9876-803654ad8ea6.png)

@davidicus It's because storybook changes that on the fly and doesn't cause a re-run of the react effect. I can add an observer to check for changes to the document.dir attribute if you want. Otherwise, if you resize the window a hair, it'll trigger the resize event and re-position the menu properly.

2021-04-26 14:29 UTC, davidicus approved these changes

2021-04-29 20:21 UTC, merged