fix(list-item): add aria-label and title to expand button
carbon-design-system/carbon-addons-iot-react pull request #2232
Opened 2021-04-20 20:48 UTC by kevinsperrine

Closes #2094 

**Summary**

- added aria-label and title attributes to the ListItem when it's expandable. 
- ❓❓❓ QUESTION: The current tests are checking for "expand" when the item is expanded and "close" when the item is closed. I would expect these to be opposite. ie. If the item is expanded, the aria-label should be "Close" to explain the purpose of that button, no?

**Acceptance Test (how to verify the PR)**

- Running the accessibility checker should not show errors for `Interactive component does not have a programmatically associated name` on the expand/contract buttons.

2021-04-21 07:52 UTC, herleraja approved these changes
LGTM

2021-04-21 17:55 UTC, davidicus requested changes

2021-04-21 17:55 UTC, davidicus commented on packages/react/src/components/List/ListItem/ListItem.jsx
> +        aria-label={expanded ? i18n.expand : i18n.close}
yes like you mentioned. This looks like it should be flipped.

2021-04-26 14:46 UTC, davidicus approved these changes

2021-04-27 20:40 UTC, merged