Table columns move
carbon-design-system/carbon-addons-iot-react pull request #2626
Opened 2021-07-30 13:32 UTC by zvonimirfras

2021-09-22 18:37 UTC, Donisius approved these changes

2021-09-23 18:30 UTC, davidicus approved these changes

2021-09-23 18:30 UTC, davidicus approved these changes

2021-09-24 12:06 UTC, davidicus requested changes
blocking merge until we can merge from master

2021-09-24 15:08 UTC, davidicus approved these changes

2021-09-27 14:21 UTC, merged