feat(card): add new datetimepicker to card as option
carbon-design-system/carbon-addons-iot-react pull request #2627
Opened 2021-08-02 17:52 UTC by scottdickerson

Closes #2454

**Summary**

- Adds a new option to the Card availableActions that will render the custom range picker

**Change List (commits, features, bugs, etc)**

- feat(Card): allow non-boolean values in the available actions
- feat(CardToolbar): add new timepicker if a availableActions.range is of type string and take additional time range options
- feat(cardToolbar): smaller font inside cards

**Acceptance Test (how to verify the PR)**

- Verify new card range picker stories send the action correctly

**Regression Test (how to make sure this PR doesn't break old functionality)**

- Verify old card range picker still works in the story.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2021-08-02 21:36 UTC, davidicus commented
Now that I see the implementation I am remembering that Diana was saying the date needs to be in the subtitle with the icons remaining icon only. From [discussion thread](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2455#issuecomment-871529449) in the other PR.

Which would require you to consume the changes from [this](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2624) PR to implement.

2021-08-02 21:37 UTC, davidicus requested changes
Code looks good but we should follow design's implementation suggestions from [this](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2624) thread

2021-08-03 15:24 UTC, davidicus approved these changes

2021-08-03 15:34 UTC, davidicus commented
#2630 has been created to align this feature with desired spec.

2021-08-03 15:39 UTC, JoelArmendariz approved these changes

2021-08-03 15:41 UTC, merged