feat(table): add `hasFastSearch` prop to toggle onChange/onBlur
carbon-design-system/carbon-addons-iot-react pull request #2874
Opened 2021-09-22 16:54 UTC by kevinsperrine

Closes #2871 

**Summary**

- add `hasFastSearch` prop to toggle search happening onChange or on `Enter` or onBlur.

**Change List (commits, features, bugs, etc)**

- add `hasFastSearch` prop to table
- set `hasFastSearch` to default to `true` to keep current behavior
- pass to TableToolbar
- add onKeyDown/onBlur handlers when `hasFastSearch:false`
- add cypress tests to cover

**Acceptance Test (how to verify the PR)**

- in the simple stateful table story, if you uncheck `hasFastSearch` the table should only update it's state when you press `Enter` or change focus away from the search box

**Regression Test (how to make sure this PR doesn't break old functionality)**

- existing search functionality should be unchanged.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2021-09-22 17:54 UTC, kevinsperrine commented
@davidicus Can you re-trigger netlify on this one? The push failed when I updated stories to add the `hasFastSearch` knob.

2021-09-23 16:38 UTC, davidicus approved these changes
Great job!

2021-09-23 19:10 UTC, bjornalm requested changes

2021-09-23 19:10 UTC, bjornalm commented on packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
> +                const value = event?.target?.value || defaultValue;
I think that the "Clear search input" in TableToolbarSearch's updates the value to be an empty string and expects this onChange method to perform the actual searchApply to clear the filter. So for the new hasFastSearch:false the search will not be cleared when the "Clear search input" is clicked.

2021-09-24 11:29 UTC, kevinsperrine commented on packages/react/cypress/plugins/index.js
> +        test: /\.mdx?$/,
b/c of the mdx files imported in the table stories, when pulling the component from it, webpack needs to know how to process the mdx documentation files.

2021-11-09 20:42 UTC, kevinsperrine commented
closing. as this was originally branched from master, and not next. reopening from next.

2021-11-09 20:42 UTC, closed without merging