chore(table): remove isSortable prop where inappropriate
carbon-design-system/carbon-addons-iot-react pull request #3021
Opened 2021-11-02 16:18 UTC by kevinsperrine

Closes #2962 

**Summary**

- removes extraneous uses of isSortable in stories/tests where not appropriate.

**Change List (commits, features, bugs, etc)**

- updated stories, tests, snapshots

**Acceptance Test (how to verify the PR)**

- isSortable should not appear as knobs in stories
- or in tests except where necessary

**Regression Test (how to make sure this PR doesn't break old functionality)**

- n/a

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2021-11-02 21:22 UTC, bjornalm requested changes
Nice, I think you missed one though. `isSortable` is also used in packages/react/src/components/Table/StatefulTable.test.jsx

2021-11-02 21:56 UTC, kevinsperrine commented
> Nice, I think you missed one though. `isSortable` is also used in packages/react/src/components/Table/StatefulTable.test.jsx

Good catch. tough to sort through and catch all of them. fixed.

2021-11-05 10:42 UTC, bjornalm approved these changes

2021-11-08 14:47 UTC, davidicus approved these changes

2021-11-08 14:48 UTC, merged