Nested table max-width prop
carbon-design-system/carbon-addons-iot-react pull request #3130
Opened 2021-12-09 12:59 UTC by cgirani

Closes #3129

**Summary**

- Add a max-width in the span, based on the nested offset.

**Change List (commits, features, bugs, etc)**

- fix(tablerow): max-width for nested table

**Acceptance Test (how to verify the PR)**

- Go to StatefulTable - with row nesting and resizable columns with initial width
- Open an item with at least 4 nested levels and see the width is not overwritten the next column

**Regression Test (how to make sure this PR doesn't break old functionality)**

- Make sure the nested table keeps working properly.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2021-12-09 21:08 UTC, kevinsperrine approved these changes
Thanks for the help. Looks great!

2021-12-10 09:50 UTC, bjornalm reviewed
Fix looks clean and simple. I just wanna test it properly before approving. I've restarted the failed deployment.

2021-12-14 09:59 UTC, bjornalm approved these changes

2021-12-14 15:47 UTC, davidicus approved these changes

2021-12-14 15:49 UTC, davidicus commented on packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
> +  max-width: calc(100% - ${(props) => props.nestingOffset}px);
We should not be doing this with styled components. This prop should be added as a css custom property.

2021-12-14 15:50 UTC, davidicus requested changes
We do not support styled components and these will be removed in the future. Any new features that need a prop value should be done using css custom properties

2021-12-14 23:26 UTC, merged