feat(list builder): add angular list builder
carbon-design-system/carbon-addons-iot-react pull request #3265
Opened 2022-02-07 02:27 UTC by Donisius

List builder component from #2806

2022-03-25 14:32 UTC, zvonimirfras requested changes

2022-03-31 15:38 UTC, Donisius commented on packages/angular/src/list-builder-index.ts
> +export { AIListBuilderComponent } from './list-builder/list-builder.component';
I like keeping the AI for all components

2022-03-31 15:44 UTC, Donisius commented on packages/angular/src/list/list-item/ai-list-item.component.ts
> +      this.itemSelected.emit();
yep

2022-04-01 14:01 UTC, zvonimirfras commented on packages/angular/src/list-builder-index.ts
> +export { AIListBuilderComponent } from './list-builder/list-builder.component';
If we don’t have the AI* for the ones that don’t exist in cca, when they “graduate” and are moved to cca, we don’t have to change much, and people using it only change the import location.
If we’re adding th AI* only for the ones that already exist in cca, it’s clear that a component is a PAL variant

2022-09-29 20:43 UTC, davidicus commented
@zvonimirfras @Donisius can we get an update to this or close it out? It is getting pretty stale.

2023-01-13 19:22 UTC, davidicus commented
closing this from lack of response. Feel free to re-open when you are ready.

2023-01-13 19:22 UTC, closed without merging