docs(dashboard-grid): add initial docs to cover DashboardGrid
carbon-design-system/carbon-addons-iot-react pull request #3273
Opened 2022-02-08 13:57 UTC by kevinsperrine

Closes #3256 

**Summary**

- add documentation to cover DashboardGrid usage

**Change List (commits, features, bugs, etc)**

- new docs

**Acceptance Test (how to verify the PR)**

- proofread docs
- check links work in [storybook docs](https://deploy-preview-3273--carbon-addons-iot-react.netlify.app/?path=/docs/1-watson-iot-dashboard-grid--dashboard-default-layouts)

**Regression Test (how to make sure this PR doesn't break old functionality)**

- n/a

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-02-14 15:05 UTC, davidicus commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +Mby passing `isResizable` to the cards in a DashboardGrid, the cards become resizable by dragging and
Typo
```suggestion
By passing `isResizable` to the cards in a DashboardGrid, the cards become resizable by dragging and
```

2022-02-15 23:14 UTC, kevinsperrine commented
> This is great! Thanks for putting this together. My only question would be, does it make sense to add a line about what you would do with `onCardSizeChange` and `onLayoutChange`.

Yeah, I added a couple lines related to that.

2022-02-16 10:43 UTC, bjornalm requested changes
Nice work, just some spelling mistakes and links that need fixing

2022-02-16 10:43 UTC, bjornalm commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +[GitHub](https://github.com/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/src/components/DashboardGrid/DashboardGrid.mdx).
Should be https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/src/components/Dashboard/DashboardGrid.mdx

2022-02-16 10:43 UTC, bjornalm commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +[Source code](https://github.com/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/src/components/DashboardGrid)
Should be https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/src/components/Dashboard/DashboardGrid.jsx

2022-02-16 10:43 UTC, bjornalm commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +Pass a custom layout to the dashboard grid to assign positions and sizes to the various to the cards.
spelling: to the various cards

2022-02-16 10:43 UTC, bjornalm commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +drop a card in a new location. The card array contains objects representing each card in the layout.
...card in the layout, similar to the layout...

2022-02-16 10:43 UTC, bjornalm commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +[is editable story](/?path=/story/1-watson-iot-dashboard-grid--dashboard-is-editable) to see the
Link is not working, remove the section `/?path=` 
Story links must start with `/story/`

2022-02-16 10:43 UTC, bjornalm commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +story](/?path=/story/1-watson-iot-dashboard-grid--dashboard-resizable-card) to see callback in action.
Remove section `/?path=`

2022-02-16 10:43 UTC, bjornalm commented on packages/react/src/components/Dashboard/DashboardGrid.mdx
> +can be used to save the layout state, so that it can be recreated later.
re-created?

2022-02-16 17:42 UTC, bjornalm approved these changes

2022-02-16 17:49 UTC, merged