feat(readonlyvalue): new component readonlyvalue
carbon-design-system/carbon-addons-iot-react pull request #3382
Opened 2022-03-18 11:56 UTC by cgirani

Closes #3124

**Summary**

- New component that displays information that is not editable in a similar structure as text inputs.  Though the information cannot be edited, a user can copy the displayed information.

**Change List (commits, features, bugs, etc)**

- New component ReadOnlyValue

**Acceptance Test (how to verify the PR)**

- Validate that the components work and is presented as the [design specs](https://pages.github.ibm.com/ai-applications/design/components/read-only-value/style) 

**Regression Test (how to make sure this PR doesn't break old functionality)**

- N/A

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-03-18 16:25 UTC, davidicus commented on packages/react/src/components/ReadOnlyValue/ReadOnlyValue.mdx
> +- [Variables](#variables)
There is no corresponding section for this part of the docs

2022-03-18 16:32 UTC, davidicus approved these changes
Looks good. Just a few minor questions and comments.

2022-03-18 22:04 UTC, cgirani commented on packages/react/src/components/ReadOnlyValue/ReadOnlyValue.jsx
> +      <span data-testid={`${testId}--value`}>{value}</span>
changed to be like this:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/22034430/159090781-7bf8cce6-1434-4bea-a20a-2069b7c4a993.png">

2022-03-21 12:23 UTC, bjornalm requested changes
Nice work, how does it handle really long values? Perhaps we can add knobs to the stories where the value and label can be modified?

2022-03-21 12:23 UTC, bjornalm commented on packages/react/src/components/ReadOnlyValue/ReadOnlyValue.jsx
> +  testId: 'testId',
We should use something less generic like `read-only-value` as the default

2022-03-21 12:23 UTC, bjornalm commented on packages/react/src/components/ReadOnlyValue/ReadOnlyValue.mdx
> +import { ReadOnlyValue } from 'carbon-addons-iot-react';
I would add a small code example of how it is used, e.g:

```
    <ReadOnlyValue label="Label 01" value="input value 01" type="stacked" />
    <ReadOnlyValue label="Label 02" value="input value 02" type="stacked" />
```

2022-03-21 12:23 UTC, bjornalm commented on packages/react/src/components/ReadOnlyValue/_read-only-value.scss
> +    display: block;
There is an outline on focus-visible that we might want to remove:
![image](https://user-images.githubusercontent.com/5167091/159258642-e1ee627c-0d4a-4b96-ad92-5d5495810916.png)

```
&:focus-visible {
    outline: unset;
}
```

2022-03-21 14:33 UTC, cgirani commented
> Nice work, how does it handle really long values? Perhaps we can add knobs to the stories where the value and label can be modified?

It will change it to be a textarea and should render something like this
![image](https://user-images.githubusercontent.com/22034430/159283575-3c97bfe4-af9a-4567-8b9f-e464ee41a302.png)

2022-03-21 19:24 UTC, merged