chore(angular): upgrade to angular 12
carbon-design-system/carbon-addons-iot-react pull request #3518
Opened 2022-08-10 11:18 UTC by siddharthcr

Closes #

**Summary**

Upgrading `@ai-apps/angular` to angular 12

**Change List (commits, features, bugs, etc)**

- upgrade to angular 12
- enabled 'partial' compilation mode with ivy
- refactored code to remove circular dependency
- upgraded storybook for to 6.5.9 and webpack 5
- refactored stories to use new story format

**Acceptance Test (how to verify the PR)**

- tests here

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-08-24 12:59 UTC, zvonimirfras requested changes
`chore` doesn't seem adequate. `feat` seem better once the breaking stuff is out.

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/.storybook/main.js
> +}
```suggestion
}

```

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/.storybook/main.js
> +  }
```suggestion
  if (!test || !(test instanceof RegExp)) {
      return false;
  }
```

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/package.json
> +    "rxjs": "^6.0.0"
`peerDependencies` should stay peer dependencies. Angular dependencies should be extended to include 12 (and maintain backwards compatibility).

rxjs should probably stay here and be removed from regular dependencies.

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/package.json
> +    "@angular/router": "12.2.16",
Dev deps (all, not just highlighted) should stay at lower versions to ensure backwards compatibility when adding new things. Integration tests cover everything else.
_It's ok to change them temporarily for testing locally._

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/package.json
> +    "@storybook/theming": "6.5.9",
It's good that these are locked versions. 👍 
@Akshat55, should they be locked at 6.2.3 instead?

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/src/date-time-picker/date-time-picker.component.ts
> -
Moving the exports changes how this is used (API) and is considered a breaking change. Can't do that in a non-major version.

Re-exporting from here should be ok if you wanna keep it out, as a preparation for the major.

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/src/list/ai-list.component.ts
> -
Same as date time exports.

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/src/package.json
> +    "@angular/core": "^12.0.0 || ^13.0.0 || ^14.0.0",
Looks like a breaking change

2022-08-24 12:59 UTC, zvonimirfras commented on packages/angular/src/package.json
> +    "carbon-components-angular": "^5.0.1"
Looks like a breaking change

2022-08-24 15:45 UTC, Akshat55 requested changes

2022-08-24 15:45 UTC, Akshat55 commented on packages/angular/src/flyout-menu/flyout-menu.stories.ts
> +
```suggestion
```

2022-08-24 15:45 UTC, Akshat55 commented on packages/angular/src/icon-content-switcher/icon-content-switcher.stories.ts
> +
```suggestion
```

2022-08-24 15:45 UTC, Akshat55 commented on packages/angular/src/tabs/tabs.stories.ts
> +
```suggestion
```

2022-08-24 15:45 UTC, Akshat55 commented on packages/angular/src/toolkit/page-header/page-header.stories.ts
> +
```suggestion
```

2022-08-24 15:45 UTC, Akshat55 commented on packages/angular/src/toolkit/sortable-list/sortable-list.stories.ts
> +
```suggestion
```

2022-08-24 15:45 UTC, Akshat55 commented on packages/angular/src/toolkit/table-settings/table-settings.stories.ts
> +
```suggestion
```

2022-09-29 20:45 UTC, davidicus commented
@Akshat55 @zvonimirfras any updates here. Trying to close out any stale PRs

2022-10-12 15:42 UTC, zvonimirfras commented
I think we're not merging this at this point.
@Akshat55 double check and close, pls 🙂

2022-10-12 18:16 UTC, Akshat55 commented
@davidicus, we aren't merging this PR now as it contains breaking changes. Will be useful in future when carbon-addons-iot-react is updated to Carbon 11 though.

2023-01-13 19:22 UTC, davidicus commented
Closing for now. Feel free to re-open when ready.

2023-01-13 19:22 UTC, closed without merging