fix(angular): disable ivy compilation
carbon-design-system/carbon-addons-iot-react pull request #3524
Opened 2022-08-24 13:19 UTC by siddharthcr

Closes #

**Summary**

- setting `enableIvy` to false to disable ivy compilation.

**Change List (commits, features, bugs, etc)**

- In angular 11, ivy enabled libraries were not meant to be published. The build script was removing the `prepublish` script that was added by `ng-packagr` to prevent Ivy enabled libs from being published.

**Acceptance Test (how to verify the PR)**

- Create a new angular 11 app and add `@ai-apps/angular` as a dependency. When build or serve targets are run in the angular 11 app, `ngcc` compiler would compile `@ai-apps/angular` to become Ivy compatible.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- Same as above

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-08-27 02:02 UTC, Akshat55 requested changes
Should be approved after integration tests have been updated/added.

2022-08-29 09:58 UTC, siddharthcr commented
@Akshat55 copied over the integration tests. Could you please take a look? Thanks

2022-08-29 14:08 UTC, Akshat55 approved these changes

2022-08-30 13:34 UTC, zvonimirfras approved these changes

2022-08-31 12:16 UTC, merged