fix(tablecardformcontent): discard threshold from columns
carbon-design-system/carbon-addons-iot-react pull request #3565
Opened 2022-09-22 20:01 UTC by vaffonso

Closes #3563
Closes https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3389

**Summary**

- Remove threshold attribute for empty threshold lists

**Change List (commits, features, bugs, etc)**

- Remove threshold attribute for empty list from content
- Remove unnecessary threshold attribute from content.columns

**Acceptance Test (how to verify the PR)**

- Go to 'Dashboard'
- Create new dashboard
- Add 3 data items
- Add some threshold to the data item (Save the dashboard)
- Remove the data item that has threshold
- goto Open JSON editor
- Click save 
- No errors displayed.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-09-23 07:40 UTC, herleraja commented on packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
> +      const filteredThresholds = cardConfig?.content?.thresholds?.filter(
I think you forgot to update the thershold in updatedContent

2022-09-23 07:47 UTC, herleraja requested changes
LGTM. One minor update needed.

2022-09-27 12:47 UTC, herleraja approved these changes
LGTM

2022-09-28 17:13 UTC, EdmondCShaffer approved these changes

2022-09-28 18:15 UTC, davidicus approved these changes

2022-09-28 18:16 UTC, merged