fix(datetimepickerv2): expose renderInPortal prop to support floating menu as a child
carbon-design-system/carbon-addons-iot-react pull request #3608
Opened 2022-10-18 20:59 UTC by jessieyan

Closes #3362 

**Summary**

- expose `renderInPortal` prop so that use can set it to false for some scenarios

Copied from issue 3362
When the `DateTimePickerV2` is rendered inside a scrollable area (inside of the body) it'll scroll along with the content instead of staying fixed in place. This is because `DateTimePickerV2` is always rendered in a portal, and positioned absolutely relative to the body. However, when it's in a section that scrolls this positioning is no longer correct. We should expose the renderInPortal prop used on the `FlyoutMenu` within the `DateTimePickerV2` to give consumers the option of rendering it in the portal or not. Additionally, this prop will need to be added to Cards so that they can pass it to the CardToolbar and eventually to the DateTimePicker for instances of cards having a built-in DateTimePicker.

**Change List (commits, features, bugs, etc)**

- added renderInPortal prop in DateTimePickerV2, Card, TableCard, CardToolBar
- test updates

**Acceptance Test (how to verify the PR)**

- go to range select or single select story
- set renderInPortal to false, we should see `flyout-tooltip` is grandchild of `date-time-picker-datepicker-flyout-container`
![image](https://user-images.githubusercontent.com/24279794/196543175-86271623-a191-4044-9fef-5d870a51f993.png)

- set renderInPortal to true,  `flyout-tooltip` is independent element outside of `date-time-picker-datepicker-flyout-container`
![image](https://user-images.githubusercontent.com/24279794/196543557-e93d0471-b375-4d0f-8f79-1a05334eeda7.png)

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-10-19 14:22 UTC, davidicus commented
@jessieyan This usually needs to have it rendered in a portal, in order to break out of an overflow:hidden container, like our cards we need to be able to do so and still have the dropdown stay with the trigger. We can either close the portal on scroll or adjust the offset so it scrolls with the element. We have components in the codebase that manipulate the offset that you can try to look for.

2022-10-19 14:23 UTC, davidicus requested changes
This is not a solution to the issue that is listed for this PR

2022-10-19 17:03 UTC, jessieyan commented
> @jessieyan This usually needs to have it rendered in a portal, in order to break out of an overflow:hidden container, like our cards we need to be able to do so and still have the dropdown stay with the trigger. We can either close the portal on scroll or adjust the offset so it scrolls with the element. We have components in the codebase that manipulate the offset that you can try to look for.

@davidicus  Do you mean the offered solution in [issue 3362](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3362) is not valid? This is the change that requested in the description of 3362 that we need to expose renderInPortal prop. It does not solve the menu offset issue though.

2022-10-24 13:47 UTC, davidicus commented
We can surface a prop to allow people to render in portal or not but we need to have the dropdown not detach even when it is rendered in portal.

2022-10-26 19:23 UTC, jessieyan commented
@davidicus Change this PR to only resolve the issue #3618 which is to enable the auto positioning

2022-10-27 21:03 UTC, davidicus commented on packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
> +    );
I think the [spec](https://jestjs.io/docs/25.x/jest-object#jestfnimplementation) suggest the following for mock implementation. 
```suggestion
    const mockGetBoundingClientRect = jest.fn(generateBoundingClientRect);
```

2022-10-28 17:06 UTC, jessieyan commented
@davidicus I saw you left a review comment earlier but I couldn't find it in the PR.

2022-10-28 18:04 UTC, davidicus commented
> @davidicus I saw you left a review comment earlier but I couldn't find it in the PR.

I had deleted the comment after I saw you were returning a function. Was supposed to be part of the review.

2022-10-31 14:49 UTC, davidicus requested changes

2022-10-31 14:57 UTC, davidicus commented
Issue with Card component and the DateTimePicker in [this](https://deploy-preview-3608--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-card-card--with-date-time-picker-range-selector) story

This PR            |  Next
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/1590966/199038652-10e6cf83-5019-4b06-a162-fdd31485062a.png) | ![image](https://user-images.githubusercontent.com/1590966/199038716-8a84ed7a-dfc8-4aec-afd1-6f5fafadf3ce.png)

2022-10-31 14:59 UTC, davidicus commented on packages/react/src/components/Card/Card.jsx
> +  renderInPortal: false,
Should this default be true? I think the DateTimePickerV2 was built specifically to render in a portal for the Cards. This is most likely why the story is broken

2022-10-31 15:11 UTC, jessieyan commented
> https://deploy-preview-3608--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select

I can see if set the padding-left to 80 rem. Then a horizontal bar showed up. The flyout menu will adjust its position if the horizontal bar moves.

2022-10-31 15:29 UTC, davidicus commented on packages/react/src/components/Card/CardToolbar.jsx
> +  renderDateDropdownInPortal: false,
I imagine this gets overwritten by Card default prop but should probably align

2022-10-31 15:32 UTC, davidicus commented on packages/react/src/constants/CardPropTypes.js
> +  renderInPortal: PropTypes.bool,
also need to rename the prop here.

2022-10-31 15:57 UTC, davidicus approved these changes
We can address some of the positioning issues in another PR.

2022-10-31 16:34 UTC, merged

2022-10-31 16:43 UTC, jessieyan commented
> I can see if set the padding-left to 80 rem. Then a horizontal bar showed up. The flyout menu will adjust its position if the horizontal bar moves. If set padding-left to 71 rem, The flyout menu will pop up on top of the input and will not move its position.

Opened #3620