fix(FlyoutMenu): Flyout menu position
carbon-design-system/carbon-addons-iot-react pull request #3627
Opened 2022-11-02 17:05 UTC by jessieyan

Closes #

**Summary**

FlyoutMenu does not move when parent is scrolling. 

**Change List (commits, features, bugs, etc)**

- added css attribute `--top` and `--left` so that FlyoutMenu can move with the parent.
- temporary updated the single story and absolute story to test
- fixed style PropTypes

**Acceptance Test (how to verify the PR)**

- go to single select story
- click on the Calendar button to open flyout menu
- scroll up and down in the red container
- scroll left and right in the red container
- notice the flyout menu is moving with the datetime input

https://user-images.githubusercontent.com/24279794/199554269-aee7c213-1872-44ea-8fa9-a335c309857d.mov

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-11-02 21:25 UTC, jessieyan commented
Fixing cypress test

2022-11-07 20:03 UTC, davidicus requested changes
I am unable to test this. I think the story was reverted back because now there is no scrolling possible.

2022-11-28 16:23 UTC, jessieyan commented
Updated the single select story for testing.

2022-11-28 19:51 UTC, jessieyan commented
Netlify is not updating the deploy build for some reason.

2022-11-29 15:49 UTC, davidicus commented
@jessieyan I manually updated the build. There are still issues. I think if you simplify by taking out the internal red div and adding your height to the outer div you will see the issue. 


https://user-images.githubusercontent.com/1590966/204576600-19fbc60a-c4b2-400d-a094-d15fbc004e71.mov

2022-11-29 15:50 UTC, davidicus commented
I am also seeing some weirdness with the positioning in [our storybook](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select). Can we try to address this altogether?
![image](https://user-images.githubusercontent.com/1590966/204576869-01f684c4-2e30-4e1b-b01f-c58d66315e6b.png)

2022-12-13 19:41 UTC, jessieyan commented
Hi @davidicus, I want to consult this with you.

When rendering `DateTimePickerV2`, the FlyoutMenu always render TimePickerDropDown with the Footer first and after a few more re-rendering, the `DatePicker` got rendered. Do you know what might cause the `DatePicker` rendered so late.

This is an issue causes the calculation of the height to be less than it should be. 

Screen shot of it first renders the time picker 
![image](https://user-images.githubusercontent.com/24279794/207428365-4e5b52dd-40da-43d7-9544-072d61a99caf.png)

After a few re-renders, it renders the date picker
![image](https://user-images.githubusercontent.com/24279794/207428437-696d8c79-34b3-4aec-9683-ed7fd254efae.png)

2023-01-06 15:45 UTC, davidicus requested changes
@jessieyan Looking good. Just the comments about cleaning up our event listeners.

2023-01-06 15:45 UTC, davidicus commented on packages/react/src/components/DateTimePicker/DateTimePickerV2WithTimeSpinner.jsx
> +    }
we need to return a function that removes these event listeners.

2023-01-06 15:45 UTC, davidicus commented on packages/react/src/components/DateTimePicker/DateTimePickerV2WithoutTimeSpinner.jsx
> +      currentNode.addEventListener('scroll', getPosition);
same comment about cleaning up our listeners

2023-01-06 17:19 UTC, davidicus approved these changes
should be good to merge once checks pass

2023-01-06 17:25 UTC, jessieyan commented
I also tested with DateTimePicker without new time spinner. It should also work as expected.

2023-01-06 17:42 UTC, merged