fix(dataseriesformsettings): Set empty strings for missing values
carbon-design-system/carbon-addons-iot-react pull request #3681
Opened 2022-12-21 19:17 UTC by vaffonso

Closes #3680

**Summary**

- Set empty string in case of null or undefined values

**Change List (commits, features, bugs, etc)**

- DataSeriesFormSettings: use nullish coalescing operator to set empty strings

**Acceptance Test (how to verify the PR)**

- Render component with all attributes from content filled
- Re-render component with some of them missing

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2022-12-26 18:09 UTC, vaffonso commented
@herleraja @EdmondCShaffer could you take a look?

2023-01-03 15:25 UTC, JordanWSmith15 commented
@davidicus FYI

2023-01-04 08:54 UTC, herleraja commented on packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
> +          value={content?.maximumDataPoints ?? ''}
its numeric value. Is there no other way we can fix this issue ?

2023-01-04 08:55 UTC, herleraja commented on packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
> +          value={content?.decimalPrecision ?? ''}
I think this is also numeric value.  May be good to add type="number"

2023-01-04 08:57 UTC, herleraja reviewed
It's fine to have an empty string literal for labels, but for numeric fields, its better be null or undefined.

2023-01-13 14:33 UTC, davidicus commented
Doing the steps outlined in this issue on this [story](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor--with-initial-value), it seems like the fields get updated.

2023-01-13 14:42 UTC, davidicus requested changes
Just the comment on the number inputs.

2023-01-17 20:13 UTC, vaffonso commented
Hi @davidicus @herleraja 
I was able to reproduce the issue in this [story](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor--with-initial-value) following these steps:
- Select timeseries card
- Switch to Settings tab
- Note that Unit, Decimal Precision and Maximum Data Points are empty
- Add new card
- Select Time Series Line
- Give it a title Test
- Switch to Settings tab
- Fill Unit, Decimal Precision and Maximum Data Points with value
- Select timeseries card again
- Note that Unit, Decimal Precision and Maximum data points value are not reset

I have commented in the original defect:

> I see 3 possible approaches:
> 1. Provide empty strings for Data Series Form Settings attributes - Monitor UI
> 2. Check null and undefined values and replace with empty strings - PAL lib (solution tested)
> 3. Apply check for null/undefined check in TextInput - Carbon lib

Should we opt for the 1st option?

2023-01-18 15:32 UTC, davidicus commented
@vaffonso can we not provide a null value for these fields?

2023-01-20 14:40 UTC, vaffonso commented
I pushed a couple changes to this PR. Instead of empty strings, number inputs from DataSeriesFormSettings receive key prop to force a render.
In addition, field **decimal precision** was changed to number.

2023-01-20 14:55 UTC, davidicus approved these changes
LGTM 👍

2023-01-20 14:56 UTC, merged