Feat 3700
carbon-design-system/carbon-addons-iot-react pull request #3752
Opened 2023-03-16 13:44 UTC by erzhan-temir-mamyrov

Closes #3700 

**Summary**

- WIP

**Change List (commits, features, bugs, etc)**

- items_here

**Acceptance Test (how to verify the PR)**

- tests here

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

2023-03-28 13:38 UTC, erzhan-temir-mamyrov commented on packages/react/src/components/Breadcrumb/Breadcrumb.story.jsx
> +  disableTruncation: text('Disable truncation (first, last)', ''),
@jessieyan For sure, thanks for the feedback! I will update this story.

2023-04-14 14:16 UTC, davidicus requested changes
<img width="998" alt="image" src="https://user-images.githubusercontent.com/1590966/232069589-eb5a9e78-eef2-4fe7-9177-87e97d19c078.png">
If we disable truncation on the last breadcrumb and they are both long we lose the entire first breadcrumb.

2023-04-18 10:15 UTC, erzhan-temir-mamyrov commented
@davidicus Thanks for the note! I added min-width property to the opposite breadcrumb to avoid compression.

2023-04-18 15:20 UTC, jessieyan commented
Loos good

2023-04-18 15:28 UTC, jessieyan approved these changes

2023-04-19 10:57 UTC, merged